### ISSUE TITLE
Force all uploaded images to be under 5MB

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_app#133]

**Comment by connor-makowski** [comment]
This should be limited in the django admin settings when uploading images (private or public).

**Comment by elaineliuwang** [comment]
Photos are now limited to a maximum 5MB in the page section for both public/private, changes are in 2.1.0-dev-file-limit branch

**Comment by connor-makowski** [comment]
https://github.com/MIT-CAVE/cave_app/pull/147
