### ISSUE TITLE
Move `settings.numberFormat` properties to `settings.defaults`

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_app#134]
I added `settings.defaults` in de259b8 to support properties like `showToolbar` that can be overwritten later. I was thinking that this is also the case with the `settings.numberFormat` properties, so we can move them to `settings.defaults` and get rid of that `numberFormat` wrapper key.

**Comment by connor-makowski** [comment]
Sounds reasonable to me. @mrkwanzaa your thoughts here?

**Comment by mrkwanzaa** [comment]
Makes sense to me
