### ISSUE TITLE
Break up API Docs into multiple files

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_app#14]
Migrate and link all API docs (`cave_app/cave_api/README_API_STRUCTURE.md`) into more organized/granular MD files. 

Keep the initial README_API_STRUCTURE.md file (since it is linked in many places) with links to each of the individual MD files.
New MD files should then be located in a `cave_app/cave_api/docs`

@erinliu1 This should be a great first issue to get you into the API Documentation, but not have to do a lot of coding yet.

@luisvasq I am hoping you can work with Erin to get this done and give her guidance. Also feel free to edit this issue towards your desired end goals here.

**Comment by luisvasq** [comment]
@erinliu1 completed this task successfully. :tada:

I've put some final touches on it and now we're ready to close this issue. However, there's a pending issue with the references in the docs. It's a cumbersome task to update references manually, but even if we do it, it's still painful when we add new references to other document sections or change our file structure. I will open a new issue to explore possible automated solutions to this problem. (Perhaps, by using a pre-processing Markdown tool.)
