### ISSUE TITLE
Add time control's `looping` and `playbackSpeed` to the API

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_app#157]
`playbackSpeed` might be renamed to `fps` or `frameRate`.

**Comment by katherineyli** [comment]
@luisvasq @connor-makowski I've changed the time control component in cave static to pull from the API, and have also updated the time setting spec to validate 'looping' and 'fps'.

**Comment by katherineyli** [comment]
cave static commit: [a4b61b](https://github.com/MIT-CAVE/cave_static/commit/a4b61b35a8b7cb1465dbd8151cf9659d7543be3b)
cave utils: [def768f](https://github.com/MIT-CAVE/cave_utils/commit/def768f7018a1bd28fdf2789bfce13365af1f933)

**Comment by luisvasq** [comment]
@katherineyli LGTM. You even took care of this in `cave_utils`! :100: Can you please add `fps` and `looping` (default values are fine) to `kitchen_sink`?

@connor-makowski, just to confirm: are you okay with the name `fps` for "animation" speed? Actually, I think we might want to specify that this refers to frames per second in the docs.

**Comment by katherineyli** [comment]
Added default values to kitchen sink: [79e7c07](https://github.com/MIT-CAVE/cave_app/commit/79e7c07c97fae904b1fbc304455e8982d1ecaaf6)

**Comment by connor-makowski** [comment]
Is it actually frames per second? I might opt to change it to `speed` with a note that we are targeting `fps` but for larger data this will be slower based on data size.

**Comment by luisvasq** [comment]
Yes, `fps` stands for frames per second. I agree. It makes sense to rename it and add a note in the docs. @katherineyli, can you please rename `fps` to `speed` in `cave_app` and `cave_static`? I'll handle `cave_utils`.

**Comment by katherineyli** [comment]
cave static commit: [3d16cb6](https://github.com/MIT-CAVE/cave_static/commit/3d16cb641a381c0d4c2ad919d3752e3ef602b98a)

**Comment by katherineyli** [comment]
Replaced useState with useCallback dispatch using mutateLocal: [690b375](https://github.com/MIT-CAVE/cave_static/commit/690b375e387cead285ec2d887986e773467db543)

**Comment by luisvasq** [comment]
@katherineyli, I confirm this is working fine! I merged your changes into `2.3.0-dev`. The `time-control-api` branch you created in `cave_utils` is protected by default since it doesn't contain `-dev` in its name (this rule exists to prevent accidental pushes to a stable branch), so I wasn't able to push to it. I added the changes for `cave_utils` in a `2.3.0-dev` branch.

@connor-makowski, can you please delete `time-control-api` in `cave_utils`?

In the meantime, we can close this one.
