### ISSUE TITLE
Stats value names cannot start with a number

### ISSUE THREAD

**Issue by erinliu1** [MIT-CAVE/cave_app#48]
I noticed that if you have a stats value that's named something like "35_type" (where the name is a string but it starts with a number), then the whole thing breaks. Maybe we can either fix that or add to the docs saying you can't name a stats starting with a number.

**Comment by mrkwanzaa** [comment]
It looks like this is a requirement of the [expr-eval](https://www.npmjs.com/package/expr-eval) package we use for stat calculations static side. Because of this I'd say we should look at adding this to the docs unless @connor-makowski has any other input here.
