### ISSUE TITLE
Exception: Session Error: No session data found. This could be caused by an incorrect `data_name` or not being in a session.

### ISSUE THREAD

**Issue by erinliu1** [MIT-CAVE/cave_app#49]
When you try to add a chart to the dashboards, you get the error "Exception: Session Error: No session data found. This could be caused by an incorrect `data_name` or not being in a session."

**Comment by mrkwanzaa** [comment]
This should be fixed by MIT-CAVE/cave_static@6ceb84eb969bf42274ba6e1a815b72a8540be96b
