### ISSUE TITLE
Update main page after login from menu bar

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_app#78]
- If you log in incorrectly, you get taken to a "login" screen on the main page.
- If you then use the icon on the menu bar to log in (NOT THE PAGE), you are signed into the website, but the "login" screen stays on the main page.

You can see that I have logged in (DHL icon at the top), but the main login screen stays at the bottom.

![Image](https://user-images.githubusercontent.com/47668639/236195270-ef2e6a36-6073-47f2-8dd3-73ef75940a4a.png)

The “login page” should switch to the “home page” as part of the login process.

**Comment by connor-makowski** [comment]
Thanks @maxtkc closing with your commit: 4de25d1e7535938b066af9c1803445c06b24c13f
