### ISSUE TITLE
Legend numberFormat for int if not using SciNotation

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_app#82]
In this example, the port throughput is an integer. The legend shows the lower value as 0.00 instead of 0. I get that it makes sense to use #.## for scientific notation, but you do not need that at the lower end if you are not using scientific notation.

![Image](https://user-images.githubusercontent.com/47668639/241070768-67c71c02-2e34-4748-a1d3-a9c1cc407e14.png)

**Comment by maxtkc** [comment]
@mrkwanzaa @luisvasq If you have a chance to check out my draft PR for some API changes, that would be great. It addresses this and [Text labels for color gradients in legend](https://github.com/MIT-CAVE/cave_static/issues/234)

**Comment by maxtkc** [comment]
Fixed in [#242](https://github.com/MIT-CAVE/cave_static/pull/242)
