### ISSUE TITLE
Why is modal creation slower with map open vs KPIs?

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_app#86]
This is a question that came up using Luc/Milena's current app. In the workshop, we are going to open the KPIs instead of having the map in the background while we create new products. Doing this significantly improves the time it takes to open modals. This is a question - is this CAVE App behavior or model behavior?

**Comment by connor-makowski** [comment]
This has to do with reloading the entire map data structure each time an update is applied. It is possible for the api creators to update their code only passing the updated `appBar` data with `wipeExisting` set to false in `kwargs`. This would prevent the forced re render.
